use x-checker-data for dependencies
flathub/com.obsproject.Studio pull request #103
Opened 2021-03-02 16:21 UTC by dgcampea

- use x-checker-data for dependencies
- update x264
- update ffmpeg to 4.3.2 and drop patch
- change luajit to versioned branch v2.1 as recommended by upstream

2021-03-06 15:42 UTC, GeorgesStavracas requested changes
The changes themselves look good to me, but I think this branch needs better commits. I'm not going to ask you to make each x-checker-data a commit of its own, but at least splitting them from the other commits should make the branch look better.

2021-03-06 15:42 UTC, GeorgesStavracas commented on com.obsproject.Studio.json
> +          "disable-shallow-clone": true
Could you please split these LUA changes into a separate commit?

2021-03-06 15:42 UTC, GeorgesStavracas commented on com.obsproject.Studio.json
> +          "sha256": "46e4e64f1dd0233cbc0934b9f1c0da676008cad34725113fb7f802cfa84ccddb",
Could you please split this into a separate commit? This one is about x264

2021-03-06 16:34 UTC, dgcampea commented on com.obsproject.Studio.json
> +            "tag-pattern": "^v([\\d.]+)$"
I'm not sure, they seem to do both (https://github.com/ARMmbed/mbedtls/tags)

2021-03-06 16:38 UTC, dgcampea commented on com.obsproject.Studio.json
> +          "branch": "master",
Is it better to leave it untouched?
Since they have no releases, anytime this gets updated manually its virtually the same thing as using x-checker-data and see if it builds/breaks.

2021-03-06 16:57 UTC, gasinvein commented on com.obsproject.Studio.json
> +            "tag-pattern": "^v([\\d.]+)$"
Maybe use json checker to query github API for latest release, then?

2021-03-06 17:20 UTC, dgcampea commented on com.obsproject.Studio.json
> +            "tag-pattern": "^v([\\d.]+)$"
Done

2021-03-06 17:21 UTC, dgcampea commented on com.obsproject.Studio.json
> +          "sha256": "46e4e64f1dd0233cbc0934b9f1c0da676008cad34725113fb7f802cfa84ccddb",
Done

2021-03-06 17:21 UTC, dgcampea commented on com.obsproject.Studio.json
> +          "disable-shallow-clone": true
Done

2021-03-08 19:24 UTC, TingPing commented on com.obsproject.Studio.json
> +          "branch": "master",
It should always be reproducible.

Every build containing a different build of x264 sucks for debugging and maintainance.

2021-03-12 12:28 UTC, GeorgesStavracas approved these changes

2021-03-12 12:29 UTC, merged